### PR TITLE
Provide a contribution link to the GitHub repository.

### PR DESCRIPTION
**Pull request by bholley**
I found the task of locating the repository to be non-trivial.

### CODE REVIEW

**Review by fluffyemily — COMMENTED** [review]
I agree that this is good information to have on our site. I think I would prefer the links to be bullet points. 

This is because it is easier to parse out information that is separated in a list than having to read a paragraph to discover whether the information you need is inside.

**Comment by bholley** [comment]
Updated.

**Review by fluffyemily — APPROVED** [review]

**Comment by bholley** [comment]
@fluffyemily Thanks! Who can merge the PR?

**Pull request merged**
